version: '3.7'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=dwh
    ports:
      - "3307:3306"
    networks:
      - all-network
    volumes:
      - mysql-db-volume:/var/lib/mysql
      - ./dwh:/dwh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=mysql
      - PMA_PASSWORD=mysql
    ports:
      - "8081:80"
    networks:
      - all-network

volumes:
  mysql-db-volume:


networks:
  all-network:
    driver: bridge
